---
title: "t-SNE plots"
author: "Matt Greenwald / Marc Ryser"
date: "09/12/2022"
output:
  pdf_document: default
  html_document: default
---

```{r, echo = FALSE, include = FALSE, warning = FALSE, message = FALSE}
#-----------------------------
#-- Libraries
#-----------------------------
library(readr)
#library(Rtreemix)
library(ggplot2)
library(ggsci)
library(scales)
library(Rtsne)

#-- color palette
pal1 <- pal_jco("default")(10)

#-- setting seed
set.seed(1238)

#-- Tumor names to input to function
#-- Excluding 222 because there are only 2 DCIS spots
Tumornames <- c("03","17","24","53","65","66","88","91","168","173","191","211","213","221","222","225","227","286","315")


#-----------------------------
#-- Parameters
#-----------------------------
purity=.8 # tumor purity
cutoff=.05 # detection threshold
c0=.5 # prior prob of a mutation being absent (delta-weight)
p.mut.no<-c0*(1+pbeta(cutoff*purity, 1, 1/purity))
prob.present <- 1-p.mut.no

#-----------------------------
#-- Function which will give a graph and the table of R values
#-----------------------------

TSNE_tables <- function(DCIS_name, prob.present){
  
  
  #reading in Tumor
  DCIS_path <- paste("/Users/mdr30/Library/CloudStorage/Box-Box/0_D5_Paper/4_Post_processing/Complete_Cleaned_Bayesian/CleanedBayesian_Tumor_", DCIS_name, ".csv", sep = "")
  Tumor <- as.data.frame(read_csv(DCIS_path))
  Tumor <- Tumor[,-1]
  
  
  #-----------------------------
  #-- Fill in NA values
  #-----------------------------
  
  #All NA's denote a prob.present probability of the mutation being present
  for(i in 1:length.POSIXlt(Tumor)){
    for(j in 13:length(Tumor)){
      if(is.na(Tumor[i,j])){
        Tumor[i,j] <- prob.present
      }
    }
  }
  
  
  #-----------------------------
  #-- Putting into correct format
  #-----------------------------
  Tumor <- Tumor[,c(1,5,13:length(Tumor))]
  Tumor <- Tumor[-1,]
  for(i in 1:length.POSIXlt(Tumor)){
    if(Tumor[i,"Histology"] == "Atypical" | Tumor[i,"Histology"] == "Non-Atypical" ){
      Tumor[i,"Histology"] <- "Benign"
    }
  }
  
  
  #-----------------------------
  #-- Histologies <- colors
  #-----------------------------
  spotcolors <- Tumor$Histology
  for(i in 1:length(spotcolors)){
    if(spotcolors[i] == "Normal"){
      spotcolors[i] <- pal1[3]
    } else if(spotcolors[i] == "Benign"){
      spotcolors[i] <- pal1[1]
    } else if(spotcolors[i] == "DCIS"){
      spotcolors[i] <- pal1[2]
    } else if(spotcolors[i] == "Invasive"){
      spotcolors[i] <- pal1[4]
    }
  }
  
  #-----------------------------
  #-- tSNE plots
  #-----------------------------
  Tumor <- Tumor[,-c(1,2)]
  perplexity <- (length.POSIXlt(Tumor)-1)/3
  tsnedata <- Rtsne(Tumor, initial_dims = length.POSIXlt(Tumor), perplexity = perplexity, check_duplicates = FALSE)
  
  return(list(spotcolors, tsnedata))
  
}

```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "03"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "17"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "24"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "53"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "65"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "66"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "88"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "91"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "168"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "173"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "191"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "211"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "213"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "222"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "225"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "227"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "286"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

#building table
DCIS_name <- "315"
output <- TSNE_tables(DCIS_name, prob.present)
Tsne_data <- output[[2]]
spotcolors <- output[[1]]

#plotting
par(mar=c(5, 5, 4.1, 8.1), xpd=TRUE)
plot(Tsne_data$Y, col = spotcolors, pch = 19, cex = 1.5, main = paste("t-SNE for Spots of Tumor", DCIS_name), xlab = "t-SNE1",ylab = "t-SNE2")
legend("topright",inset=c(-0.35,0), c("Normal", "Benign","DCIS", "Invasive"), col = c(pal1[c(3,1,2,4)]), pch = 16)
```